// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418155409_AllowGlobalReviewSessions")]
    partial class AllowGlobalReviewSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Card", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CardType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CardSentence", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("text");

                    b.Property<string>("SentenceId")
                        .HasColumnType("text");

                    b.Property<List<string>>("AnswerList")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("BlankWord")
                        .HasColumnType("text");

                    b.Property<string>("Hint")
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("CardId", "SentenceId");

                    b.HasIndex("SentenceId");

                    b.HasIndex("CardId", "Position")
                        .HasDatabaseName("idx_card_sentences_card_position");

                    b.ToTable("card_sentences", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Deck", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CardsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<int>("FoldersCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("ForkedFromId")
                        .HasColumnType("text");

                    b.Property<bool>("IsOfficial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TypeId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Public");

                    b.HasKey("Id");

                    b.HasIndex("ForkedFromId")
                        .HasDatabaseName("idx_decks_forked_from");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("idx_decks_type_id");

                    b.HasIndex("CreatedBy", "CreatedAt")
                        .HasDatabaseName("idx_decks_owner_created_at");

                    b.HasIndex("Visibility", "Status")
                        .HasDatabaseName("idx_decks_visibility_status");

                    b.ToTable("decks", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DeckBookmark", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeckId")
                        .HasColumnType("text");

                    b.Property<DateTime>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "DeckId");

                    b.HasIndex("DeckId")
                        .HasDatabaseName("idx_deck_bookmarks_deck_id");

                    b.ToTable("deck_bookmarks", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DeckFolder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CardsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeckId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeckId", "Position")
                        .HasDatabaseName("idx_deck_folders_deck_position");

                    b.ToTable("deck_folders", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DeckType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("deck_types", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FolderCard", b =>
                {
                    b.Property<string>("FolderId")
                        .HasColumnType("text");

                    b.Property<string>("CardId")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeckId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("FolderId", "CardId");

                    b.HasIndex("CardId")
                        .HasDatabaseName("idx_folder_cards_card_id");

                    b.HasIndex("DeckId", "CardId")
                        .IsUnique()
                        .HasDatabaseName("uq_folder_cards_deck_card");

                    b.HasIndex("DeckId", "FolderId");

                    b.HasIndex("FolderId", "Position")
                        .HasDatabaseName("idx_folder_cards_folder_position");

                    b.ToTable("folder_cards", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GrammarDetail", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("text");

                    b.Property<List<string>>("AlternateForms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Caution")
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<int?>("Register")
                        .HasColumnType("integer");

                    b.Property<string>("Structures")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("structures");

                    b.HasKey("CardId");

                    b.ToTable("grammar_details", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GrammarRelation", b =>
                {
                    b.Property<string>("GrammarId")
                        .HasColumnType("text");

                    b.Property<string>("RelatedId")
                        .HasColumnType("text");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer");

                    b.HasKey("GrammarId", "RelatedId", "RelationType");

                    b.HasIndex("RelatedId");

                    b.ToTable("grammar_relations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GrammarResource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("grammar_resources", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KanjiDetail", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("text");

                    b.Property<string>("HanViet")
                        .HasColumnType("text");

                    b.Property<string>("Kanji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Kunyomi")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MeaningVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Onyomi")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("StrokeCount")
                        .HasColumnType("integer");

                    b.Property<string>("StrokeOrderUrl")
                        .HasColumnType("text");

                    b.HasKey("CardId");

                    b.HasIndex("Kanji")
                        .IsUnique();

                    b.HasIndex("StrokeCount");

                    b.ToTable("kanji_details", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KanjiRadical", b =>
                {
                    b.Property<string>("KanjiId")
                        .HasColumnType("text");

                    b.Property<string>("RadicalId")
                        .HasColumnType("text");

                    b.HasKey("KanjiId", "RadicalId");

                    b.HasIndex("RadicalId");

                    b.ToTable("kanji_radicals", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MediaAsset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UsageType", "CreatedAt");

                    b.ToTable("MediaAssets", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.NoteLike", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NoteId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "NoteId");

                    b.HasIndex("NoteId");

                    b.ToTable("note_likes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RadicalDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KanjiCardId")
                        .HasColumnType("text");

                    b.Property<string>("MeaningVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Character")
                        .IsUnique();

                    b.HasIndex("KanjiCardId");

                    b.ToTable("radical_details", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Sentence", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SpeakerId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("sentences", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.StudySession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<List<string>>("CardIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("CompletedCardIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<int>("CorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeckId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FlashcardBack")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Summary");

                    b.Property<string>("FlashcardFront")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Title");

                    b.Property<int>("IncorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MultipleChoiceQuestion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("TitleToSummary");

                    b.Property<List<string>>("SelectedFolderIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<bool>("ShuffleOptions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("UserId", "CompletedAt")
                        .HasDatabaseName("idx_study_sessions_user_completed");

                    b.ToTable("study_sessions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("User");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserCardNote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LikesCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId", "CardId")
                        .IsUnique();

                    b.ToTable("user_card_notes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserCardProgress", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CardId")
                        .HasColumnType("text");

                    b.Property<int>("ConsecutiveCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsMastered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSentenceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SrsLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("level_1");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "CardId");

                    b.HasIndex("CardId");

                    b.HasIndex("LastSentenceId");

                    b.HasIndex("UserId", "NextReviewAt")
                        .HasDatabaseName("idx_user_card_progress_user_next_review");

                    b.ToTable("user_card_progress", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserLearningSettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FlashcardBack")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Summary");

                    b.Property<string>("FlashcardFront")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Title");

                    b.Property<string>("MultipleChoiceQuestion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("TitleToSummary");

                    b.Property<bool>("ShuffleOptions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId");

                    b.ToTable("user_learning_settings", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VocabularyDetail", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("text");

                    b.Property<List<string>>("Antonyms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<string>("PitchAccent")
                        .HasColumnType("text");

                    b.Property<string>("Reading")
                        .HasColumnType("text");

                    b.Property<List<string>>("RelatedPhrases")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("SpeakerId")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Synonyms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("WordType")
                        .HasColumnType("integer");

                    b.Property<string>("Writing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CardId");

                    b.ToTable("vocabulary_details", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Card", b =>
                {
                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Domain.Entities.CardSentence", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithMany("CardSentences")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sentence", "Sentence")
                        .WithMany("CardSentences")
                        .HasForeignKey("SentenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Sentence");
                });

            modelBuilder.Entity("Domain.Entities.Deck", b =>
                {
                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany("CreatedDecks")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Deck", "ForkedFrom")
                        .WithMany("Forks")
                        .HasForeignKey("ForkedFromId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.DeckType", "Type")
                        .WithMany("Decks")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");

                    b.Navigation("ForkedFrom");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Entities.DeckBookmark", b =>
                {
                    b.HasOne("Domain.Entities.Deck", "Deck")
                        .WithMany("Bookmarks")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("DeckBookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.DeckFolder", b =>
                {
                    b.HasOne("Domain.Entities.Deck", "Deck")
                        .WithMany("Folders")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Domain.Entities.FolderCard", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithMany("FolderCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Deck", "Deck")
                        .WithMany("FolderCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DeckFolder", "Folder")
                        .WithMany("FolderCards")
                        .HasForeignKey("DeckId", "FolderId")
                        .HasPrincipalKey("DeckId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Domain.Entities.GrammarDetail", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithOne("GrammarDetail")
                        .HasForeignKey("Domain.Entities.GrammarDetail", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Domain.Entities.GrammarRelation", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Grammar")
                        .WithMany()
                        .HasForeignKey("GrammarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Card", "Related")
                        .WithMany()
                        .HasForeignKey("RelatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grammar");

                    b.Navigation("Related");
                });

            modelBuilder.Entity("Domain.Entities.GrammarResource", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithMany("GrammarResources")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Domain.Entities.KanjiDetail", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithOne("KanjiDetail")
                        .HasForeignKey("Domain.Entities.KanjiDetail", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Domain.Entities.KanjiRadical", b =>
                {
                    b.HasOne("Domain.Entities.Card", "KanjiCard")
                        .WithMany("KanjiRadicals")
                        .HasForeignKey("KanjiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.RadicalDetail", "Radical")
                        .WithMany("KanjiRadicals")
                        .HasForeignKey("RadicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanjiCard");

                    b.Navigation("Radical");
                });

            modelBuilder.Entity("Domain.Entities.MediaAsset", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("MediaAssets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.NoteLike", b =>
                {
                    b.HasOne("Domain.Entities.UserCardNote", "Note")
                        .WithMany("NoteLikes")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RadicalDetail", b =>
                {
                    b.HasOne("Domain.Entities.Card", "KanjiCard")
                        .WithMany()
                        .HasForeignKey("KanjiCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KanjiCard");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.StudySession", b =>
                {
                    b.HasOne("Domain.Entities.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("StudySessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserCardNote", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithMany("UserCardNotes")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserCardProgress", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithMany("UserCardProgresses")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sentence", "LastSentence")
                        .WithMany()
                        .HasForeignKey("LastSentenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("CardProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("LastSentence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserLearningSettings", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("LearningSettings")
                        .HasForeignKey("Domain.Entities.UserLearningSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.VocabularyDetail", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithOne("VocabularyDetail")
                        .HasForeignKey("Domain.Entities.VocabularyDetail", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.ValueObjects.MeaningItem", "Meanings", b1 =>
                        {
                            b1.Property<string>("VocabularyDetailCardId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<List<string>>("Definitions")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<int>("PartOfSpeech")
                                .HasColumnType("integer");

                            b1.HasKey("VocabularyDetailCardId", "Id");

                            b1.ToTable("vocabulary_details");

                            b1.ToJson("meanings");

                            b1.WithOwner()
                                .HasForeignKey("VocabularyDetailCardId");
                        });

                    b.Navigation("Card");

                    b.Navigation("Meanings");
                });

            modelBuilder.Entity("Domain.Entities.Card", b =>
                {
                    b.Navigation("CardSentences");

                    b.Navigation("FolderCards");

                    b.Navigation("GrammarDetail");

                    b.Navigation("GrammarResources");

                    b.Navigation("KanjiDetail");

                    b.Navigation("KanjiRadicals");

                    b.Navigation("UserCardNotes");

                    b.Navigation("UserCardProgresses");

                    b.Navigation("VocabularyDetail");
                });

            modelBuilder.Entity("Domain.Entities.Deck", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("FolderCards");

                    b.Navigation("Folders");

                    b.Navigation("Forks");
                });

            modelBuilder.Entity("Domain.Entities.DeckFolder", b =>
                {
                    b.Navigation("FolderCards");
                });

            modelBuilder.Entity("Domain.Entities.DeckType", b =>
                {
                    b.Navigation("Decks");
                });

            modelBuilder.Entity("Domain.Entities.RadicalDetail", b =>
                {
                    b.Navigation("KanjiRadicals");
                });

            modelBuilder.Entity("Domain.Entities.Sentence", b =>
                {
                    b.Navigation("CardSentences");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("CardProgresses");

                    b.Navigation("CreatedDecks");

                    b.Navigation("DeckBookmarks");

                    b.Navigation("LearningSettings");

                    b.Navigation("MediaAssets");

                    b.Navigation("StudySessions");
                });

            modelBuilder.Entity("Domain.Entities.UserCardNote", b =>
                {
                    b.Navigation("NoteLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
