// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412150020_AddKanjiModule")]
    partial class AddKanjiModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Card", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CardType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CardSentence", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("text");

                    b.Property<string>("SentenceId")
                        .HasColumnType("text");

                    b.HasKey("CardId", "SentenceId");

                    b.HasIndex("SentenceId");

                    b.ToTable("card_sentences", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GrammarDetail", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("text");

                    b.Property<List<string>>("AlternateForms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Caution")
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<int?>("Register")
                        .HasColumnType("integer");

                    b.Property<string>("Structures")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("structures");

                    b.HasKey("CardId");

                    b.ToTable("grammar_details", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GrammarRelation", b =>
                {
                    b.Property<string>("GrammarId")
                        .HasColumnType("text");

                    b.Property<string>("RelatedId")
                        .HasColumnType("text");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer");

                    b.HasKey("GrammarId", "RelatedId", "RelationType");

                    b.HasIndex("RelatedId");

                    b.ToTable("grammar_relations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GrammarResource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("grammar_resources", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KanjiDetail", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("text");

                    b.Property<string>("HanViet")
                        .HasColumnType("text");

                    b.Property<string>("Kanji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Kunyomi")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MeaningVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Onyomi")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("StrokeCount")
                        .HasColumnType("integer");

                    b.Property<string>("StrokeOrderUrl")
                        .HasColumnType("text");

                    b.HasKey("CardId");

                    b.HasIndex("Kanji")
                        .IsUnique();

                    b.HasIndex("StrokeCount");

                    b.ToTable("kanji_details", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KanjiRadical", b =>
                {
                    b.Property<string>("KanjiId")
                        .HasColumnType("text");

                    b.Property<string>("RadicalId")
                        .HasColumnType("text");

                    b.HasKey("KanjiId", "RadicalId");

                    b.HasIndex("RadicalId");

                    b.ToTable("kanji_radicals", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MediaAsset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UsageType", "CreatedAt");

                    b.ToTable("MediaAssets", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.NoteLike", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NoteId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "NoteId");

                    b.HasIndex("NoteId");

                    b.ToTable("note_likes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RadicalDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KanjiCardId")
                        .HasColumnType("text");

                    b.Property<string>("MeaningVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Character")
                        .IsUnique();

                    b.HasIndex("KanjiCardId");

                    b.ToTable("radical_details", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Sentence", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SpeakerId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("sentences", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("User");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserCardNote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LikesCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId", "CardId")
                        .IsUnique();

                    b.ToTable("user_card_notes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VocabularyDetail", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("text");

                    b.Property<List<string>>("Antonyms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<string>("PitchAccent")
                        .HasColumnType("text");

                    b.Property<string>("Reading")
                        .HasColumnType("text");

                    b.Property<List<string>>("RelatedPhrases")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("SpeakerId")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Synonyms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("WordType")
                        .HasColumnType("integer");

                    b.Property<string>("Writing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CardId");

                    b.ToTable("vocabulary_details", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Card", b =>
                {
                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Domain.Entities.CardSentence", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithMany("CardSentences")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sentence", "Sentence")
                        .WithMany("CardSentences")
                        .HasForeignKey("SentenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Sentence");
                });

            modelBuilder.Entity("Domain.Entities.GrammarDetail", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithOne("GrammarDetail")
                        .HasForeignKey("Domain.Entities.GrammarDetail", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Domain.Entities.GrammarRelation", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Grammar")
                        .WithMany()
                        .HasForeignKey("GrammarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Card", "Related")
                        .WithMany()
                        .HasForeignKey("RelatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grammar");

                    b.Navigation("Related");
                });

            modelBuilder.Entity("Domain.Entities.GrammarResource", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithMany("GrammarResources")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Domain.Entities.KanjiDetail", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithOne("KanjiDetail")
                        .HasForeignKey("Domain.Entities.KanjiDetail", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Domain.Entities.KanjiRadical", b =>
                {
                    b.HasOne("Domain.Entities.Card", "KanjiCard")
                        .WithMany("KanjiRadicals")
                        .HasForeignKey("KanjiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.RadicalDetail", "Radical")
                        .WithMany("KanjiRadicals")
                        .HasForeignKey("RadicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanjiCard");

                    b.Navigation("Radical");
                });

            modelBuilder.Entity("Domain.Entities.MediaAsset", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("MediaAssets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.NoteLike", b =>
                {
                    b.HasOne("Domain.Entities.UserCardNote", "Note")
                        .WithMany("NoteLikes")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RadicalDetail", b =>
                {
                    b.HasOne("Domain.Entities.Card", "KanjiCard")
                        .WithMany()
                        .HasForeignKey("KanjiCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KanjiCard");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserCardNote", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithMany("UserCardNotes")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.VocabularyDetail", b =>
                {
                    b.HasOne("Domain.Entities.Card", "Card")
                        .WithOne("VocabularyDetail")
                        .HasForeignKey("Domain.Entities.VocabularyDetail", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.ValueObjects.MeaningItem", "Meanings", b1 =>
                        {
                            b1.Property<string>("VocabularyDetailCardId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<List<string>>("Definitions")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<int>("PartOfSpeech")
                                .HasColumnType("integer");

                            b1.HasKey("VocabularyDetailCardId", "Id");

                            b1.ToTable("vocabulary_details");

                            b1.ToJson("meanings");

                            b1.WithOwner()
                                .HasForeignKey("VocabularyDetailCardId");
                        });

                    b.Navigation("Card");

                    b.Navigation("Meanings");
                });

            modelBuilder.Entity("Domain.Entities.Card", b =>
                {
                    b.Navigation("CardSentences");

                    b.Navigation("GrammarDetail");

                    b.Navigation("GrammarResources");

                    b.Navigation("KanjiDetail");

                    b.Navigation("KanjiRadicals");

                    b.Navigation("UserCardNotes");

                    b.Navigation("VocabularyDetail");
                });

            modelBuilder.Entity("Domain.Entities.RadicalDetail", b =>
                {
                    b.Navigation("KanjiRadicals");
                });

            modelBuilder.Entity("Domain.Entities.Sentence", b =>
                {
                    b.Navigation("CardSentences");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("MediaAssets");
                });

            modelBuilder.Entity("Domain.Entities.UserCardNote", b =>
                {
                    b.Navigation("NoteLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
